### ISSUE TITLE
truffle console throws null accounts error

### ISSUE THREAD

**Issue by GurpreetSK95** [maheshmurthy/ethereum_voting_dapp#2]
On running command truffle console or truffle migrate, the following error is thrown everytime even accounts exist. 
```
/usr/local/lib/node_modules/truffle/lib/environment.js:66
        config.networks[config.network].from = accounts[0];
                                                       ^

TypeError: Cannot read property '0' of null
    at /usr/local/lib/node_modules/truffle/lib/environment.js:66:56
    at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/property.js:119:13
    at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:119:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by maheshmurthy** [comment]
Please open if you still have this issue
