### ISSUE TITLE
Web3 js not working properly 

### ISSUE THREAD

**Issue by harshil15999** [maheshmurthy/ethereum_voting_dapp#26]
Promise failed to return 
> deployedContract.deploy({
...   data: bytecode,
...   arguments: [listOfCandidates.map(name => web3.utils.asciiToHex(name))]
... }).send({
...   from: 'ENTER 1 OF 10 ACCOUNT ADDRESSES like 0xfb3....',
...   gas: 1500000,
...   gasPrice: web3.utils.toWei('0.00003', 'ether')
... }).then((newContractInstance) => {
...   deployedContract.options.address = newContractInstance.options.address
...   console.log(newContractInstance.options.address)
... });

**
Uncaught:
Error: Provided address "ENTER 1 OF 10 ACCOUNT ADDRESSES like 0xfb3...." is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
    at Object.inputAddressFormatter (F:\ethereum_voting_dapp-master\ethereum_voting_dapp-master\chapter1\node_modules\web3-core-helpers\lib\formatters.js:398:11)
    at Contract.getOrSetDefaultOptions [as _getOrSetDefaultOptions] (F:\ethereum_voting_dapp-master\ethereum_voting_dapp-master\chapter1\node_modules\web3-eth-contract\lib\index.js:304:66)
    at Object._processExecuteArguments (F:\ethereum_voting_dapp-master\ethereum_voting_dapp-master\chapter1\node_modules\web3-eth-contract\lib\index.js:700:42)
    at Object._executeMethod (F:\ethereum_voting_dapp-master\ethereum_voting_dapp-master\chapter1\node_modules\web3-eth-contract\lib\index.js:720:68)**

**Comment by harshil15999** [comment]
PLEASE MAKE SURE TO FILL THE ADDRESSES
